
language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

jobs:
  include:
    - php: 7.1
      env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-stable"
    - php: 7.4
      env: COVERAGE="--coverage-clover build/logs/clover.xml"
    - php: 7.4
      script: composer stan
    - php: 7.4
      script: composer cs

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit $COVERAGE

after_script:
  - if [ "$COVERAGE" != "" ]; then vendor/bin/php-coveralls --verbose || true; fi

